config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'front#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :profile
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
	belongs_to :user
	delegate :username, to: :user
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:username]

	attr_accessor :username

	belongs_to :role
	has_one :profile

	before_validation :set_default_role
	before_create :build_profile

	def admin?
	self.role.name == "admin"
	end

	def registered?
	self.role.name == "registered"
	end
	
	def name
  		"#{first_name} #{last_name}"
  	end

  	validate :validate_username

  	def validate_username
		if User.where(email: username).exists?
		  errors.add(:username, :invalid)
		end
	end

	validates :email, 
	        presence: true,
	        uniqueness: { :case_sensitive => false },
	        format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\Z/ }

	validates :username, 
	        presence: true,  
	        length: { in: 3..30 },
	        uniqueness: { :case_sensitive => false },
	        format: { with: /\A[a-zA-Z0-9]+\Z/ }

	def self.find_for_database_authentication(warden_conditions)
		conditions = warden_conditions.dup
		if login = conditions.delete(:login)
		  where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
		elsif conditions.has_key?(:username) || conditions.has_key?(:email)
		  where(conditions.to_h).first
		end
	end
	
	def update_with_password(params={}) 
	  if params[:password].blank? 
	    params.delete(:password) 
	    params.delete(:password_confirmation) if params[:password_confirmation].blank? 
	  end 
	  update_attributes(params) 
	end

	private
	
	def set_default_role
	  self.role ||= Role.find_by_role('registered')
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :remember_me]
    lockdown = [:email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: lockdown
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_path, :alert => exception.message
  end
end

app/controllers/front_controller.rb
class FrontController < ApplicationController
  def index
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
	
  def show
  	@profile =  User.where(username: params[:id]).first!.profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/front_helper.rb
module FrontHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/front/index.html.erb
<%= stylesheet_link_tag 'top-bar' %>
<div class="banner">
	<div class="home">
		<h1 class="home-title">Training for 3D Designers</h1>
		<div class="cell">
			<p>رؤية مختلفة لمستقبل افضل</p>
			<%= link_to "Create FREE Account", new_user_registration_path, class: "button secondary btn btn--1" %>
			<a class="hollow button btn btn--2" href="#">Explore Our Screencasts</a>
		</div>
	</div>
</div>

app/views/layouts/_fb.html.erb
<div >
	<%= link_to image_tag("msg.png"), "https://m.me/abdouelshazly", class: "wd",
	 onclick: "return !window.open(this.href, 'fb', 'width=650,height=800')",
    target: "_blank" %>
</div>

app/views/layouts/_header.html.erb
  <div class="header">
    <div class="row">
      <div class="top-bar-left">
        <%= link_to image_tag("Dlogo.png"), root_path, class: "Dlogo" %>
        <%= link_to image_tag("Wlogo.png"), root_path, class: "Wlogo" %>
      </div>
      
      <div class="title-bar-right" >
          <span data-responsive-toggle="responsive-menu" data-hide-for="medium">
            <button class="hamburger" type="button" data-open="offCanvas">
              <span class="line"></span>
              <span class="line"></span>
              <span class="line"></span>
            </button>
          </span>
      </div>
        
      <div class="top-bar-right" id="responsive-menu" data-hide-for="large" >
        <ul class="dropdown menu" data-dropdown-menu>
          
          <li><%# link_to 'Blog', posts_path  %></li>
          <li><%# link_to "Screencasts", episodes_path %></li>
          <li><%= link_to "Admin", rails_admin_path %></li>
          <li><% if user_signed_in? %>
            <li><%= link_to (image_tag (current_user.profile.avatar)), profile_path(current_user.username), class: "avatar" %>
              <ul class="dropdown menu" data-dropdown-menu>
                <li><%= link_to "Profile", profile_path(current_user.username) %></li>
                <li><%= link_to "Sitting", edit_user_registration_path %></li><br>
                <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
              </ul>
            </li>
            <% else %>
            <li><%= link_to 'Join Us', new_user_session_path  %></li>
            <% end %>
          </li>
        </ul>
      </div>

    </div>
  </div>


app/views/layouts/_offcanvas.html.erb
<button class="close">
0
</button>

<button class="close-button" aria-label="Close menu" type="button" data-close>
	<span class="line" aria-hidden="true"></span>
	<span class="line" aria-hidden="true"></span>
</button>


<ul class="vertical menu drawer-nav">
	<li><a href="#">One</a></li>
	<li><a href="#">Two</a></li>
	<li><%= link_to "Admin", rails_admin_path %></li>
	<li><% if user_signed_in? %>
	  <li><%= link_to current_user.username, edit_user_registration_path %>
	    <ul class="dropdown menu" data-dropdown-menu>
	      <li>
	        <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
	      </li>
	    </ul>
	  </li>
	  <% else %>
	  <li>
	    <%= link_to 'Login', new_user_session_path  %>
	  </li>
	  <% end %>
	</li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Guzoor | جذور</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= favicon_link_tag "favicon.ico" %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/js/foundation.min.js' %>
  </head>

  <body>
    <% if notice %>
     <div class="success callout text-center note">
        <p><%= notice %></p>
      </div>      
    <% elsif alert %>
      <div class="alert callout text-center note">
        <p><%= alert %></p>
      </div>    
    <% end %>

    <div class="off-canvas position-top" id="offCanvas" data-off-canvas data-transition="overlap">
      <%= render 'layouts/offcanvas' %>
    </div>

    <div class="off-canvas-content" data-off-canvas-content>
      <%= render 'layouts/header' %>
      <%= yield %>    
  </div>
  <%= render 'layouts/fb' %>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up for an account", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>